//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRumahSakit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAIL_TRANSAKSI_RUANGAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DETAIL_TRANSAKSI_RUANGAN()
        {
            this.TRANSAKSIs = new HashSet<TRANSAKSI>();
        }
    
        public int DETIL_RUANGAN_ID { get; set; }
        public Nullable<int> RUANGAN_ID { get; set; }
        public Nullable<int> JUMLAH_HARI { get; set; }
        public Nullable<int> SUBTOTAL { get; set; }
    
        public virtual RUANGAN RUANGAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSAKSI> TRANSAKSIs { get; set; }
    }
}
