//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRumahSakit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETIL_TRANSAKSI_OBAT
    {
        public int DETIL_OBAT_ID { get; set; }
        public Nullable<int> OBAT_ID { get; set; }
        public Nullable<int> TRANSAKSI_ID { get; set; }
        public Nullable<int> JUMLAH { get; set; }
        public Nullable<int> SUBTOTAL { get; set; }
    
        public virtual OBAT OBAT { get; set; }
        public virtual TRANSAKSI TRANSAKSI { get; set; }
    }
}
