//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRumahSakit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOKTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOKTER()
        {
            this.RELASI_JADWAL_DOKTER = new HashSet<RELASI_JADWAL_DOKTER>();
            this.RELASI_TRANSAKSI_DOKTER = new HashSet<RELASI_TRANSAKSI_DOKTER>();
        }
    
        public int DOKTER_ID { get; set; }
        public Nullable<int> SPECIALIS_ID { get; set; }
        public Nullable<int> POLI_ID { get; set; }
        public string NAMA { get; set; }
        public string ALAMAT { get; set; }
        public string NO_TELP { get; set; }
        public Nullable<bool> JENIS_KELAMIN { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual POLI POLI { get; set; }
        public virtual SPECIALI SPECIALI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELASI_JADWAL_DOKTER> RELASI_JADWAL_DOKTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELASI_TRANSAKSI_DOKTER> RELASI_TRANSAKSI_DOKTER { get; set; }
    }
}
