//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRumahSakit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JADWAL_DOKTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JADWAL_DOKTER()
        {
            this.RELASI_JADWAL_DOKTER = new HashSet<RELASI_JADWAL_DOKTER>();
        }
    
        public int JADWAL_ID { get; set; }
        public string HARI { get; set; }
        public Nullable<System.DateTime> JAM_MULAI { get; set; }
        public Nullable<System.DateTime> JAM_SELESAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELASI_JADWAL_DOKTER> RELASI_JADWAL_DOKTER { get; set; }
    }
}
