//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRumahSakit.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBRSEntities3 : DbContext
    {
        public DBRSEntities3()
            : base("name=DBRSEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DETAIL_TRANSAKSI_RUANGAN> DETAIL_TRANSAKSI_RUANGAN { get; set; }
        public virtual DbSet<DETIL_TRANSAKSI_OBAT> DETIL_TRANSAKSI_OBAT { get; set; }
        public virtual DbSet<DOKTER> DOKTERs { get; set; }
        public virtual DbSet<JADWAL_DOKTER> JADWAL_DOKTER { get; set; }
        public virtual DbSet<JADWAL_PERAWAT> JADWAL_PERAWAT { get; set; }
        public virtual DbSet<JENIS_OBAT> JENIS_OBAT { get; set; }
        public virtual DbSet<JENIS_RUANGAN> JENIS_RUANGAN { get; set; }
        public virtual DbSet<OBAT> OBATs { get; set; }
        public virtual DbSet<PASIEN> PASIENs { get; set; }
        public virtual DbSet<PEGAWAI> PEGAWAIs { get; set; }
        public virtual DbSet<PERAWAT> PERAWATs { get; set; }
        public virtual DbSet<POLI> POLIs { get; set; }
        public virtual DbSet<RAWAT_INAP> RAWAT_INAP { get; set; }
        public virtual DbSet<RELASI_JADWAL_DOKTER> RELASI_JADWAL_DOKTER { get; set; }
        public virtual DbSet<RELASI_JADWAL_PERAWAT> RELASI_JADWAL_PERAWAT { get; set; }
        public virtual DbSet<RELASI_TRANSAKSI_DOKTER> RELASI_TRANSAKSI_DOKTER { get; set; }
        public virtual DbSet<RELASI_TRANSAKSI_PEGAWAI> RELASI_TRANSAKSI_PEGAWAI { get; set; }
        public virtual DbSet<RELASI_TRANSAKSI_PERAWAT> RELASI_TRANSAKSI_PERAWAT { get; set; }
        public virtual DbSet<ROLE> ROLEs { get; set; }
        public virtual DbSet<RUANGAN> RUANGANs { get; set; }
        public virtual DbSet<SPECIALI> SPECIALIS { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TIPE_POLI> TIPE_POLI { get; set; }
        public virtual DbSet<TRANSAKSI> TRANSAKSIs { get; set; }
    }
}
