//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRumahSakit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OBAT()
        {
            this.DETIL_TRANSAKSI_OBAT = new HashSet<DETIL_TRANSAKSI_OBAT>();
        }
    
        public int OBAT_ID { get; set; }
        public Nullable<int> JENIS_OBAT_ID { get; set; }
        public string NAMA { get; set; }
        public Nullable<int> HARGA { get; set; }
        public Nullable<int> STOCK { get; set; }
        public string DESKRIPSI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETIL_TRANSAKSI_OBAT> DETIL_TRANSAKSI_OBAT { get; set; }
        public virtual JENIS_OBAT JENIS_OBAT { get; set; }
    }
}
