//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRumahSakit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERAWAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERAWAT()
        {
            this.RELASI_JADWAL_PERAWAT = new HashSet<RELASI_JADWAL_PERAWAT>();
            this.RELASI_TRANSAKSI_PERAWAT = new HashSet<RELASI_TRANSAKSI_PERAWAT>();
        }
    
        public int PERAWAT_ID { get; set; }
        public string NAMA { get; set; }
        public string ALAMAT { get; set; }
        public string NO_TELP { get; set; }
        public Nullable<bool> JENIS_KELAMIN { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELASI_JADWAL_PERAWAT> RELASI_JADWAL_PERAWAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELASI_TRANSAKSI_PERAWAT> RELASI_TRANSAKSI_PERAWAT { get; set; }
    }
}
