//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRumahSakit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POLI()
        {
            this.DOKTERs = new HashSet<DOKTER>();
        }
    
        public int POLI_ID { get; set; }
        public Nullable<int> TIPE_POLI_ID { get; set; }
        public string NAMA { get; set; }
        public Nullable<int> HARGA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOKTER> DOKTERs { get; set; }
        public virtual TIPE_POLI TIPE_POLI { get; set; }
    }
}
