//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRumahSakit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAWAT_INAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RAWAT_INAP()
        {
            this.TRANSAKSIs = new HashSet<TRANSAKSI>();
        }
    
        public int RAWAT_INAP_ID { get; set; }
        public Nullable<System.DateTime> TGL_MASUK { get; set; }
        public Nullable<System.DateTime> TGL_KELUAR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSAKSI> TRANSAKSIs { get; set; }
    }
}
