//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRumahSakit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELASI_TRANSAKSI_PEGAWAI
    {
        public int TRANSAKSI_PEGAWAI_ID { get; set; }
        public int PEGAWAI_ID { get; set; }
        public int TRANSAKSI_ID { get; set; }
    
        public virtual PEGAWAI PEGAWAI { get; set; }
        public virtual TRANSAKSI TRANSAKSI { get; set; }
    }
}
