//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRumahSakit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELASI_JADWAL_PERAWAT
    {
        public int JADWAL_PERAWAT_ID { get; set; }
        public Nullable<int> PERAWAT_ID { get; set; }
        public Nullable<int> JADWAL_ID { get; set; }
    
        public virtual JADWAL_PERAWAT JADWAL_PERAWAT { get; set; }
        public virtual PERAWAT PERAWAT { get; set; }
    }
}
