//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRumahSakit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELASI_TRANSAKSI_DOKTER
    {
        public int TRANSAKSI_DOKTER_ID { get; set; }
        public Nullable<int> DOKTER_ID { get; set; }
        public Nullable<int> TRANSAKSI_ID { get; set; }
    
        public virtual DOKTER DOKTER { get; set; }
        public virtual TRANSAKSI TRANSAKSI { get; set; }
    }
}
