//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRumahSakit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUANGAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RUANGAN()
        {
            this.DETAIL_TRANSAKSI_RUANGAN = new HashSet<DETAIL_TRANSAKSI_RUANGAN>();
        }
    
        public int RUANGAN_ID { get; set; }
        public Nullable<int> JENIS_RUANGAN_ID { get; set; }
        public string NAMA { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAIL_TRANSAKSI_RUANGAN> DETAIL_TRANSAKSI_RUANGAN { get; set; }
        public virtual JENIS_RUANGAN JENIS_RUANGAN { get; set; }
    }
}
