//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRumahSakit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSAKSI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANSAKSI()
        {
            this.DETIL_TRANSAKSI_OBAT = new HashSet<DETIL_TRANSAKSI_OBAT>();
            this.RELASI_TRANSAKSI_DOKTER = new HashSet<RELASI_TRANSAKSI_DOKTER>();
            this.RELASI_TRANSAKSI_PEGAWAI = new HashSet<RELASI_TRANSAKSI_PEGAWAI>();
            this.RELASI_TRANSAKSI_PERAWAT = new HashSet<RELASI_TRANSAKSI_PERAWAT>();
        }
    
        public int TRANSAKSI_ID { get; set; }
        public Nullable<int> PASIEN_ID { get; set; }
        public Nullable<int> DETIL_RUANGAN_ID { get; set; }
        public Nullable<int> RAWAT_INAP_ID { get; set; }
        public byte[] TANGGAL_TRANSAKSI { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string KELUHAN { get; set; }
        public Nullable<int> TOTALHARGA { get; set; }
    
        public virtual DETAIL_TRANSAKSI_RUANGAN DETAIL_TRANSAKSI_RUANGAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETIL_TRANSAKSI_OBAT> DETIL_TRANSAKSI_OBAT { get; set; }
        public virtual PASIEN PASIEN { get; set; }
        public virtual RAWAT_INAP RAWAT_INAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELASI_TRANSAKSI_DOKTER> RELASI_TRANSAKSI_DOKTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELASI_TRANSAKSI_PEGAWAI> RELASI_TRANSAKSI_PEGAWAI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELASI_TRANSAKSI_PERAWAT> RELASI_TRANSAKSI_PERAWAT { get; set; }
    }
}
